import type { GameType, Language } from './types';

export type UiCopy = {
  locale:string; gameLabels:Record<GameType,string>; modeDescriptions:Record<GameType,string>;
  settings:string; heroTag:string; heroLine1:string; heroLine2:string; gameMode:string; change:string; mix:string; mixDescription:string;
  play:string; resume:string; newGame:string; livesChallenge:string; pointsLives:(score:string,lives:number)=>string;
  bestScore:string; bestCombo:string; accuracy:string; howTo:string; level:(level:number)=>string; bonus:string; record:string;
  pause:string; paused:string; pausedText:string; continue:string; home:string; gameOver:string; points:string; newRecord:string; replay:string;
  chooseModeTag:string; chooseMode:string; difficulty:(value:number)=>string; score:string; lives:(value:number)=>string;
  correct:string; wrong:string; lifeLost:string; timeUp:string; wellDone:string; lifeBack:string; combo:(value:number)=>string;
  oldestFirst:string; validateOrder:string; firstLetter:string; attempts:(used:number,max:number)=>string; wordleHelp:string;
  enterWord:(length:number)=>string; mustStart:(letter:string)=>string; alreadyUsed:string; attemptsLeft:(count:number)=>string;
  showHint:string; hintCost:string; yourAnswer:string;
  rulesTitle:string; rule1Title:string; rule1Text:string; rule2Title:string; rule2Text:string; rule3Title:string; rule3Text:string; rule4Title:string; rule4Text:string;
  offline:string; offlineText:string; sound:string; soundText:string; vibrations:string; vibrationsText:string; reduceMotion:string; reduceMotionText:string; contrast:string; contrastText:string; localData:string;
};

const gameLabelsFr: Record<GameType,string> = { mcq:'QCM express', boolean:'Vrai ou faux', odd:'L’intrus', order:'Remets dans l’ordre', anagram:'Anagramme', missing:'Mot à trous', clues:'Trois indices', wordle:'Mot mystère' };
const gameLabelsPl: Record<GameType,string> = { mcq:'Quiz wyboru', boolean:'Prawda czy fałsz', odd:'Znajdź intruza', order:'Ułóż kolejność', anagram:'Anagram', missing:'Brakujące litery', clues:'Trzy wskazówki', wordle:'Tajemnicze słowo' };

export const ui: Record<Language,UiCopy> = {
  fr: {
    locale:'fr-FR', gameLabels:gameLabelsFr,
    modeDescriptions:{mcq:'Quatre réponses, une seule juste',boolean:'Décide si l’affirmation est vraie',odd:'Repère l’élément qui ne va pas',order:'Replace les événements dans le temps',anagram:'Remets les lettres dans l’ordre',missing:'Complète les lettres absentes',clues:'Trouve le mot avec trois indices',wordle:'Trouve le mot mystère en six essais'},
    settings:'Réglages',heroTag:'QUIZ · MOTS · RECORDS',heroLine1:'Joue avec ta tête.',heroLine2:'Va toujours plus loin.',gameMode:'MODE DE JEU',change:'Changer ›',mix:'Mix infini',mixDescription:'Les huit mini-jeux s’enchaînent',play:'▶ Jouer',resume:'▶ Reprendre',newGame:'Nouvelle partie',livesChallenge:'3 vies · défi sans fin',pointsLives:(s,l)=>`${s} pts · ${l} vie${l>1?'s':''}`,bestScore:'Meilleur score',bestCombo:'Meilleur combo',accuracy:'Précision',howTo:'Comment jouer ?',level:n=>`Niveau ${n}`,bonus:'★ Défi vie bonus',record:'Record',pause:'Mettre en pause',paused:'En pause',pausedText:'Ton chrono est arrêté.\nTa partie est sauvegardée.',continue:'Continuer',home:'Retour à l’accueil',gameOver:'PARTIE TERMINÉE',points:'points',newRecord:'✨ Nouveau record !',replay:'Rejouer',chooseModeTag:'TA PARTIE, TES RÈGLES',chooseMode:'Choisis ton mode',difficulty:n=>`difficulté ${n}/5`,score:'SCORE',lives:n=>`${n} vies`,correct:'Bien joué !',wrong:'Pas cette fois !',lifeLost:'−1 VIE',timeUp:'Temps écoulé !',wellDone:'Bien joué !',lifeBack:'Vie récupérée !',combo:n=>`Combo ×${n} !`,oldestFirst:'Du plus ancien au plus récent',validateOrder:'Valider l’ordre',firstLetter:'Première lettre offerte',attempts:(u,m)=>`${u} essai${u>1?'s':''} sur ${m}`,wordleHelp:'Vert : bien placée · Jaune : présente',enterWord:n=>`Entre un mot de ${n} lettres.`,mustStart:l=>`Le mot doit commencer par ${l}.`,alreadyUsed:'Ce mot a déjà été proposé.',attemptsLeft:n=>`${n} essai${n>1?'s':''} restant${n>1?'s':''}.`,showHint:'+ Voir un indice',hintCost:'−35 pts',yourAnswer:'TA RÉPONSE',rulesTitle:'Comment jouer ?',rule1Title:'Enchaîne les défis',rule1Text:'Huit mini-jeux alternent culture générale et jeux de mots.',rule2Title:'Protège tes vies',rule2Text:'Tu commences avec trois cœurs. Une erreur ou un chrono écoulé en coûte un.',rule3Title:'Fais monter le combo',rule3Text:'Les séries de bonnes réponses multiplient tes points jusqu’à ×3.',rule4Title:'Décroche une vie bonus',rule4Text:'Après 25 bonnes réponses consécutives, réussis le défi bonus pour récupérer un cœur.',offline:'100 % hors ligne',offlineText:'Après la première visite, Motissimo fonctionne sans connexion.',sound:'Sons',soundText:'Effets de réussite et d’erreur',vibrations:'Vibrations',vibrationsText:'Retour tactile pendant la partie',reduceMotion:'Réduire les animations',reduceMotionText:'Limite les mouvements visuels',contrast:'Contraste renforcé',contrastText:'Améliore la distinction des éléments',localData:'Les réglages, statistiques et records restent uniquement sur cet appareil.'
  },
  pl: {
    locale:'pl-PL', gameLabels:gameLabelsPl,
    modeDescriptions:{mcq:'Cztery odpowiedzi, tylko jedna poprawna',boolean:'Oceń, czy zdanie jest prawdziwe',odd:'Wskaż element, który nie pasuje',order:'Ułóż wydarzenia w czasie',anagram:'Ułóż litery we właściwej kolejności',missing:'Uzupełnij brakujące litery',clues:'Odgadnij słowo z trzech wskazówek',wordle:'Odgadnij słowo w sześciu próbach'},
    settings:'Ustawienia',heroTag:'QUIZ · SŁOWA · REKORDY',heroLine1:'Graj z głową.',heroLine2:'Sięgaj coraz dalej.',gameMode:'TRYB GRY',change:'Zmień ›',mix:'Nieskończony miks',mixDescription:'Osiem minigier jedna po drugiej',play:'▶ Graj',resume:'▶ Wznów',newGame:'Nowa gra',livesChallenge:'3 życia · gra bez końca',pointsLives:(s,l)=>`${s} pkt · ${l} ${l===1?'życie':l>=2&&l<=4?'życia':'żyć'}`,bestScore:'Najlepszy wynik',bestCombo:'Najlepsza seria',accuracy:'Skuteczność',howTo:'Jak grać?',level:n=>`Poziom ${n}`,bonus:'★ Wyzwanie o życie',record:'Rekord',pause:'Wstrzymaj grę',paused:'Pauza',pausedText:'Czas został zatrzymany.\nGra jest zapisana.',continue:'Kontynuuj',home:'Powrót do ekranu głównego',gameOver:'KONIEC GRY',points:'punktów',newRecord:'✨ Nowy rekord!',replay:'Zagraj ponownie',chooseModeTag:'TWOJA GRA, TWOJE ZASADY',chooseMode:'Wybierz tryb',difficulty:n=>`trudność ${n}/5`,score:'WYNIK',lives:n=>`${n} ${n===1?'życie':n>=2&&n<=4?'życia':'żyć'}`,correct:'Brawo!',wrong:'Nie tym razem!',lifeLost:'−1 ŻYCIE',timeUp:'Czas minął!',wellDone:'Brawo!',lifeBack:'Odzyskane życie!',combo:n=>`Seria ×${n}!`,oldestFirst:'Od najstarszego do najnowszego',validateOrder:'Zatwierdź kolejność',firstLetter:'Pierwsza litera gratis',attempts:(u,m)=>`${u} z ${m} prób`,wordleHelp:'Zielony: dobre miejsce · Żółty: jest w słowie',enterWord:n=>`Wpisz słowo mające ${n} liter.`,mustStart:l=>`Słowo musi zaczynać się na ${l}.`,alreadyUsed:'To słowo zostało już użyte.',attemptsLeft:n=>`Pozostało prób: ${n}.`,showHint:'+ Pokaż wskazówkę',hintCost:'−35 pkt',yourAnswer:'TWOJA ODPOWIEDŹ',rulesTitle:'Jak grać?',rule1Title:'Rozwiązuj kolejne wyzwania',rule1Text:'Osiem minigier łączy wiedzę ogólną i zabawy słowne.',rule2Title:'Chroń swoje życia',rule2Text:'Zaczynasz z trzema życiami. Błąd lub koniec czasu kosztuje jedno życie.',rule3Title:'Buduj serię',rule3Text:'Kolejne poprawne odpowiedzi mnożą punkty maksymalnie razy trzy.',rule4Title:'Zdobądź dodatkowe życie',rule4Text:'Po 25 poprawnych odpowiedziach z rzędu ukończ bonus, aby odzyskać życie.',offline:'100% offline',offlineText:'Po pierwszej wizycie Motissimo działa bez połączenia z internetem.',sound:'Dźwięki',soundText:'Efekty poprawnej i błędnej odpowiedzi',vibrations:'Wibracje',vibrationsText:'Informacja dotykowa podczas gry',reduceMotion:'Ogranicz animacje',reduceMotionText:'Zmniejsza ilość ruchu na ekranie',contrast:'Większy kontrast',contrastText:'Ułatwia rozróżnianie elementów',localData:'Ustawienia, statystyki i rekordy są przechowywane tylko na tym urządzeniu.'
  }
};
